version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: SuperMegaPassword
      MYSQL_USER: solwen
      MYSQL_DATABASE: stocktrack
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
